This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./II2202-report.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file II2202-report.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file II2202-report.acr....done (14 lines written, 0 warnings).
Output written in II2202-report.acr.
Transcript written in II2202-report.alg.
